username: yourMailID
password: Password
phone_number: 7899569686

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'


positions:
- Software Engineer
- Software Developer
- Java Developer
- Spring Developer
- GoLang Developer


locations:
- Bengaluru
- Remote

salary: 60,000
rate: 25
# --------- Optional Parameters -------
uploads:
  Resume: C:\Users\pavan\Downloads\Pavan_NV_Resume.pdf
  Cover Letter: C:\Users\pavan\Downloads\Pavan_NV_Resume.pdf
  #Photo: # PATH TO photo


output_filename:
- /Users/pavan/Desktop/Linkedin/LinkedIn-Easy-Apply-Bot/out.csv

# blacklist:
- Alten

experience_level:
  # - 1 # Entry level
  - 2 # Associate
  - 3 # Mid-Senior level
  # - 4 # Director
  # - 5 # Executive
  # - 6 # Internship